# -*- coding: utf-8 -*-
"""paper1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CGDDdbvkU56dfeyKp2bEPPmu55wJmAXv
"""

from google.colab import drive
drive.mount('/content/drive')

from pathlib import Path
base = Path('/content/drive/MyDrive/Paper1')
print("folder exists:", base.exists())
if base.exists():
    print("contents:", [p.name for p in base.iterdir()])

from pathlib import Path
# is the folder where we think it is?
base = Path('/content/drive/MyDrive/Paper1')
print("folder exists:", base.exists())
if base.exists():
    print("contents:", [p.name for p in base.iterdir()])
else:
    print("searching for Paper1 ...")
    for p in Path('/content/drive/MyDrive').rglob('Paper1'):
        print("  found:", p)

import pandas as pd
from pathlib import Path

# Point this at the Paper1 folder (Colab: mount Drive first, then set the path)
DATA_DIR = Path("/content/drive/MyDrive/Paper1")   # EDIT if your mount path differs

ops = pd.read_csv(DATA_DIR / "operations.csv.gz")
print("operations shape:", ops.shape)
print("columns:", list(ops.columns))

print("\n--- department counts ---")
print(ops["department"].value_counts().to_string())

print("\n--- anesthesia type (antype) ---")
print(ops["antype"].value_counts(dropna=False).to_string())

print("\n--- ORTHO (department == 'OS') ---")
os_ops = ops[ops["department"] == "OS"]
print("ortho operations:", len(os_ops))
print("\northo antype breakdown:")
print(os_ops["antype"].value_counts(dropna=False).to_string())
print("\ntop ICD-10-PCS prefixes in ortho (first 5 chars):")
print(os_ops["icd10_pcs"].astype(str).str[:5].value_counts().head(25).to_string())

print("\n--- ASA distribution (ortho) ---")
print(os_ops["asa"].value_counts(dropna=False).to_string())
print("\n--- ICU admission present? (ortho) ---")
print("with icuin_time:", os_ops["icuin_time"].notna().sum(), "of", len(os_ops))

import numpy as np

# --- build ortho cohort ---
os_ops = ops[ops["department"] == "OS"].copy()

# primary outcome: hospital LOS in days (discharge - admission, relative-time minutes)
os_ops["los_days"] = (os_ops["discharge_time"] - os_ops["admission_time"]) / (60*24)

# secondary outcome: postoperative ICU admission
os_ops["icu_admit"] = os_ops["icuin_time"].notna().astype(int)

# exposure: General vs Neuraxial (head-to-head); drop tiny Regional/MAC for primary
cohort = os_ops[os_ops["antype"].isin(["General", "Neuraxial"])].copy()
cohort["neuraxial"] = (cohort["antype"] == "Neuraxial").astype(int)

# procedure group from ICD-10-PCS
def proc_group(code):
    c = str(code)
    if c[:4] in ("0SRC","0SRD","0SR9","0SRB","0SRA","0SRE"): return "arthroplasty"
    if c[:3] == "0SG": return "spinal_fusion"
    return "other_ortho"
cohort["proc_group"] = cohort["icd10_pcs"].apply(proc_group)

# basic cleaning: drop impossible LOS
cohort = cohort[(cohort["los_days"] >= 0) & (cohort["los_days"] < 365)]

print("cohort n:", len(cohort))
print("\nanesthesia type:")
print(cohort["antype"].value_counts().to_string())

print("\n--- LOS (days) by anesthesia type ---")
print(cohort.groupby("antype")["los_days"].describe()[["count","mean","50%","std"]].round(2).to_string())

print("\n--- ICU admission rate by anesthesia type ---")
print(cohort.groupby("antype")["icu_admit"].mean().round(3).to_string())

print("\n--- procedure groups ---")
print(cohort["proc_group"].value_counts().to_string())

print("\n--- missingness in key covariates ---")
for col in ["age","sex","asa","emop"]:
    print(f"{col}: {cohort[col].isna().sum()} missing")

import numpy as np, pandas as pd
import statsmodels.api as sm
import statsmodels.formula.api as smf

# ---- arthroplasty ICD-10-PCS codes (hip + knee replacement) ----
ARTHRO_CODES = ["0SRC","0SRD","0SR9","0SRB","0SRA","0SRE"]

def run_cohort(df, label):
    print("="*64); print("COHORT:", label)
    df = df.copy()
    # outcomes
    df["los_days"] = (df["discharge_time"] - df["admission_time"])/(60*24)
    df = df[(df["los_days"] > 0) & (df["los_days"] < 365)]      # drop impossible LOS
    df["los_days"] = df["los_days"].clip(lower=0.5)              # Gamma needs strictly >0
    df["icu_admit"] = df["icuin_time"].notna().astype(int)
    # exposure + covariates
    df["neuraxial"] = (df["antype"]=="Neuraxial").astype(int)
    df["female"] = (df["sex"]=="F").astype(int)
    def asa_cat(x):
        if pd.isna(x): return np.nan
        return "1-2" if x<=2 else "3+"
    df["asa_cat"] = df["asa"].apply(asa_cat)
    def pg(c):
        c=str(c)
        if c[:4] in ("0SRC","0SRD"): return "knee"
        if c[:4] in ("0SR9","0SRB","0SRA","0SRE"): return "hip"
        if c[:3]=="0SG": return "spine"
        return "other"
    df["proc"] = df["icd10_pcs"].apply(pg)

    d = df.dropna(subset=["los_days","neuraxial","age","female","asa_cat","emop"]).copy()
    print(f"complete-case n: {len(d):,}  (dropped {len(df)-len(d)} for missing covariates)")

    # descriptive: LOS & ICU by anesthesia
    print("\nLOS (days) by anesthesia:")
    print(d.groupby("antype")["los_days"].agg(["count","mean","median"]).round(2).to_string())
    print("\nICU admission rate by anesthesia:")
    print(d.groupby("antype")["icu_admit"].mean().round(3).to_string())

    def tbl(m):
        ci=m.conf_int()
        return pd.DataFrame({"est":np.exp(m.params),"low":np.exp(ci[0]),
                             "high":np.exp(ci[1]),"p":m.pvalues}).round(3)

    # For arthroplasty, proc has only hip/knee; for all-ortho it has 4 levels
    proc_term = "C(proc)" if d["proc"].nunique() > 1 else ""
    rhs = "neuraxial + age + female + C(asa_cat) + emop" + (" + "+proc_term if proc_term else "")

    print("\nPRIMARY  LOS  (Gamma, log link) -> est = RATIO OF MEAN LOS:")
    m1 = smf.glm(f"los_days ~ {rhs}", data=d,
                 family=sm.families.Gamma(link=sm.families.links.Log())).fit()
    print(tbl(m1).to_string())

    print("\nSECONDARY  ICU admission  (logistic) -> est = ODDS RATIO:")
    m2 = smf.logit(f"icu_admit ~ {rhs}", data=d).fit(disp=False)
    print(tbl(m2).to_string())
    return d, m1, m2

# PRIMARY: arthroplasty
arth = ops[(ops["department"]=="OS") &
           (ops["icd10_pcs"].astype(str).str[:4].isin(ARTHRO_CODES)) &
           (ops["antype"].isin(["General","Neuraxial"]))]
d_arth, m1_arth, m2_arth = run_cohort(arth, "ARTHROPLASTY (primary)")

# SENSITIVITY: all orthopedic surgery
allos = ops[(ops["department"]=="OS") & (ops["antype"].isin(["General","Neuraxial"]))]
d_all, m1_all, m2_all = run_cohort(allos, "ALL ORTHO (sensitivity)")

import numpy as np, pandas as pd
import statsmodels.api as sm
import statsmodels.formula.api as smf

d = d_arth.copy()   # arthroplasty cohort from the previous cell

# ---------- TABLE 1: baseline characteristics by anesthesia ----------
def table1(df, group="antype"):
    rows=[]
    for g,sub in df.groupby(group):
        rows.append({"anesthesia":g,"n":len(sub),
            "age_mean":round(sub["age"].mean(),1),
            "female_%":round(100*sub["female"].mean(),1),
            "ASA_3+_%":round(100*(sub["asa_cat"]=="3+").mean(),1),
            "emergency_%":round(100*sub["emop"].mean(),1),
            "knee_%":round(100*(sub["proc"]=="knee").mean(),1),
            "LOS_median":round(sub["los_days"].median(),1),
            "ICU_%":round(100*sub["icu_admit"].mean(),1)})
    return pd.DataFrame(rows)
print("TABLE 1 — arthroplasty, by anesthesia type")
print(table1(d).to_string(index=False))

# ---------- standardized mean differences (balance) ----------
d["asa3"]=(d["asa_cat"]=="3+").astype(int); d["knee"]=(d["proc"]=="knee").astype(int)
def smd(df,var,w=None):
    t=df[df.neuraxial==1]; c=df[df.neuraxial==0]
    if w is None:
        mt,mc=t[var].mean(),c[var].mean(); vt,vc=t[var].var(),c[var].var()
    else:
        wt,wc=w[df.neuraxial==1],w[df.neuraxial==0]
        mt=np.average(t[var],weights=wt); mc=np.average(c[var],weights=wc)
        vt=np.average((t[var]-mt)**2,weights=wt); vc=np.average((c[var]-mc)**2,weights=wc)
    return (mt-mc)/np.sqrt((vt+vc)/2+1e-9)

# ---------- propensity score + stabilized IPTW ----------
ps_m = smf.logit("neuraxial ~ age + female + C(asa_cat) + emop + C(proc)",
                 data=d).fit(disp=False)
d["ps"] = ps_m.predict(d)
p_treat = d["neuraxial"].mean()
d["iptw"] = np.where(d.neuraxial==1, p_treat/d.ps, (1-p_treat)/(1-d.ps))
cap = d["iptw"].quantile(0.99); d["iptw"] = d["iptw"].clip(upper=cap)  # trim extremes

print("\nBalance (standardized mean difference; <0.1 = well balanced):")
print(f"{'covariate':10s} {'before':>8s} {'after':>8s}")
for v in ["age","female","asa3","emop","knee"]:
    print(f"{v:10s} {smd(d,v):+8.3f} {smd(d,v,d['iptw']):+8.3f}")

def tbl(m):
    ci=m.conf_int()
    return pd.DataFrame({"est":np.exp(m.params),"low":np.exp(ci[0]),
                         "high":np.exp(ci[1]),"p":m.pvalues}).round(3)

print("\nIPTW-WEIGHTED PRIMARY  LOS (Gamma log) -> ratio of mean LOS:")
m1 = smf.glm("los_days ~ neuraxial + age + female + C(asa_cat) + emop + C(proc)",
             data=d, family=sm.families.Gamma(link=sm.families.links.Log()),
             freq_weights=d["iptw"]).fit()
print(tbl(m1).loc[["neuraxial"]].to_string())

print("\nIPTW-WEIGHTED SECONDARY  ICU admission (logistic) -> OR:")
m2 = smf.glm("icu_admit ~ neuraxial + age + female + C(asa_cat) + emop + C(proc)",
             data=d, family=sm.families.Binomial(), freq_weights=d["iptw"]).fit()
print(tbl(m2).loc[["neuraxial"]].to_string())

import pandas as pd, numpy as np
import statsmodels.api as sm
import statsmodels.formula.api as smf
from pathlib import Path

DATA_DIR = Path('/content/drive/MyDrive/Paper1')
ops = pd.read_csv(DATA_DIR / "operations.csv.gz")
print("loaded ops:", ops.shape)

import numpy as np, pandas as pd

d = d_arth.copy()
d["asa3"] = (d["asa_cat"]=="3+").astype(int)
d["knee"] = (d["proc"]=="knee").astype(int)

# ---------- FULL TABLE 1 with standardized mean differences ----------
def smd(df,var):
    t=df[df.neuraxial==1][var]; c=df[df.neuraxial==0][var]
    return (t.mean()-c.mean())/np.sqrt((t.var()+c.var())/2+1e-9)

labels = {"age":"Age (years)","female":"Female","asa3":"ASA 3+",
          "emop":"Emergency","knee":"Knee (vs hip)",
          "los_days":"LOS (days)","icu_admit":"ICU admission"}
rows=[]
for v in ["age","female","asa3","emop","knee","los_days","icu_admit"]:
    g=d[d.neuraxial==0][v]; nx=d[d.neuraxial==1][v]
    rows.append({"variable":labels[v],
                 "General (n=%d)"%(d.neuraxial==0).sum(): round(g.mean(),3),
                 "Neuraxial (n=%d)"%(d.neuraxial==1).sum(): round(nx.mean(),3),
                 "SMD": round(smd(d,v),3)})
table1 = pd.DataFrame(rows)
print("TABLE 1 — arthroplasty cohort, by anesthesia type")
print(table1.to_string(index=False))

# ---------- STROBE flow counts ----------
os_all      = ops[ops["department"]=="OS"]
os_gn       = os_all[os_all["antype"].isin(["General","Neuraxial"])]
ARTHRO=["0SRC","0SRD","0SR9","0SRB","0SRA","0SRE"]
os_arth_raw = os_gn[os_gn["icd10_pcs"].astype(str).str[:4].isin(ARTHRO)]
flow = pd.DataFrame({
    "step":["Orthopedic operations (dept=OS)",
            "General or Neuraxial anesthesia",
            "Arthroplasty procedure codes",
            "Complete covariates (analytic cohort)"],
    "n":[len(os_all), len(os_gn), len(os_arth_raw), len(d)]})
flow["excluded"] = flow["n"].shift(1) - flow["n"]
print("\nSTROBE FLOW")
print(flow.to_string(index=False))

# ---------- SAVE artifacts to Drive (checkpoint) ----------
OUT = DATA_DIR   # /content/drive/MyDrive/Paper1
d.to_csv(OUT/"arthroplasty_cohort.csv", index=False)
table1.to_csv(OUT/"table1.csv", index=False)
flow.to_csv(OUT/"strobe_flow.csv", index=False)
print(f"\nSaved: arthroplasty_cohort.csv, table1.csv, strobe_flow.csv -> {OUT}")

import numpy as np, pandas as pd
import matplotlib.pyplot as plt
from math import sqrt

d = d_arth.copy()
NAVY="#1f3a5f"; TEAL="#2a9d8f"
OUT = DATA_DIR   # /content/drive/MyDrive/Paper1

# ---- Figure A: LOS distribution by anesthesia type ----
cap = np.percentile(d["los_days"], 97)          # cap extreme tail for display only
fig, ax = plt.subplots(figsize=(7,4), dpi=200)
for grp,color in [("General",NAVY),("Neuraxial",TEAL)]:
    v = d.loc[d.antype==grp,"los_days"].clip(upper=cap)
    ax.hist(v, bins=30, alpha=0.55, label=grp, color=color, density=True)
ax.set_xlabel("Length of stay (days; capped at 97th percentile for display)")
ax.set_ylabel("Density"); ax.legend(frameon=False)
ax.set_title("Length of stay distribution by anesthesia type", fontweight="bold", loc="left")
ax.spines[["top","right"]].set_visible(False)
fig.savefig(OUT/"figA_los_distribution.png", bbox_inches="tight", facecolor="white")
plt.close(fig)

# ---- Figure B: violin/box of LOS by group ----
fig, ax = plt.subplots(figsize=(6,4), dpi=200)
data = [d.loc[d.antype=="General","los_days"].clip(upper=cap),
        d.loc[d.antype=="Neuraxial","los_days"].clip(upper=cap)]
vp = ax.violinplot(data, showmedians=True)
for i,b in enumerate(vp["bodies"]):
    b.set_facecolor([NAVY,TEAL][i]); b.set_alpha(0.5)
ax.set_xticks([1,2]); ax.set_xticklabels(["General\n(n=%d)"%(d.antype=="General").sum(),
                                          "Neuraxial\n(n=%d)"%(d.antype=="Neuraxial").sum()])
ax.set_ylabel("Length of stay (days; capped for display)")
ax.set_title("Length of stay by anesthesia type", fontweight="bold", loc="left")
ax.spines[["top","right"]].set_visible(False)
fig.savefig(OUT/"figB_los_violin.png", bbox_inches="tight", facecolor="white")
plt.close(fig)

# ---- Figure C: ICU admission rate with 95% CI ----
fig, ax = plt.subplots(figsize=(5,4), dpi=200)
labels=["General","Neuraxial"]; rates=[]; errs=[]
for g in labels:
    x=d.loc[d.antype==g,"icu_admit"]; p=x.mean(); nn=len(x)
    rates.append(100*p); errs.append(100*1.96*sqrt(p*(1-p)/nn))
ax.bar(labels, rates, yerr=errs, color=[NAVY,TEAL], capsize=5, width=0.6)
for i,r in enumerate(rates): ax.text(i, r+0.5, f"{r:.1f}%", ha="center", fontsize=10)
ax.set_ylabel("ICU admission (%)")
ax.set_title("ICU admission rate by anesthesia type", fontweight="bold", loc="left")
ax.spines[["top","right"]].set_visible(False)
fig.savefig(OUT/"figC_icu_rate.png", bbox_inches="tight", facecolor="white")
plt.close(fig)

print("Saved figA_los_distribution.png, figB_los_violin.png, figC_icu_rate.png to", OUT)

from google.colab import files
import zipfile, os

OUT = DATA_DIR   # /content/drive/MyDrive/Paper1

# collect every PNG in the Paper1 folder
pngs = [f for f in os.listdir(OUT) if f.lower().endswith(".png")]
print("found figures:", pngs)

zip_path = "/content/paper1_figures.zip"
with zipfile.ZipFile(zip_path, "w") as z:
    for f in pngs:
        z.write(OUT / f, arcname=f)

print(f"zipped {len(pngs)} figures -> {zip_path}")
files.download(zip_path)   # triggers browser download

import numpy as np, pandas as pd
import statsmodels.formula.api as smf
from sklearn.metrics import roc_auc_score

d = d_arth.copy()

# derive ALL columns BEFORE slicing into groups
d["female"] = (d["sex"]=="F").astype(int)
d["asa3"]   = (d["asa_cat"]=="3+").astype(int)
d["knee"]   = (d["proc"]=="knee").astype(int)
d["bmi"]    = d["weight"] / (d["height"]/100)**2
d.loc[(d.bmi<10)|(d.bmi>70), "bmi"] = np.nan          # drop implausible BMI

G = d[d.neuraxial==0]; N = d[d.neuraxial==1]
def smd_cont(a,b): return (a.mean()-b.mean())/np.sqrt((a.var()+b.var())/2+1e-9)
def smd_bin(a,b):
    pa,pb=a.mean(),b.mean(); return (pa-pb)/np.sqrt((pa*(1-pa)+pb*(1-pb))/2+1e-9)

rows=[]
def cont_row(name,col,fmt="mean"):
    g,nn=G[col].dropna(),N[col].dropna(); miss=int(d[col].isna().sum())
    if fmt=="median":
        gv=f"{g.median():.1f} [{g.quantile(.25):.1f}\u2013{g.quantile(.75):.1f}]"
        nv=f"{nn.median():.1f} [{nn.quantile(.25):.1f}\u2013{nn.quantile(.75):.1f}]"
    else:
        gv=f"{g.mean():.1f} ({g.std():.1f})"; nv=f"{nn.mean():.1f} ({nn.std():.1f})"
    rows.append([name,gv,nv,round(smd_cont(g,nn),3),miss])
def bin_row(name,col):
    g,nn=G[col],N[col]; miss=int(d[col].isna().sum())
    rows.append([name,f"{int(g.sum())} ({100*g.mean():.1f})",
                 f"{int(nn.sum())} ({100*nn.mean():.1f})",round(smd_bin(g,nn),3),miss])
def cat_row(name,col):
    miss=int(d[col].isna().sum())
    for lvl in sorted(d[col].dropna().unique()):
        g=(G[col]==lvl); nn=(N[col]==lvl)
        rows.append([f"{name}: {lvl}",f"{int(g.sum())} ({100*g.mean():.1f})",
                     f"{int(nn.sum())} ({100*nn.mean():.1f})",round(smd_bin(g,nn),3),miss])

cont_row("Age, mean (SD)","age")
bin_row("Female, n (%)","female")
cont_row("BMI, mean (SD)","bmi")
cont_row("Weight (kg), mean (SD)","weight")
cont_row("Height (cm), mean (SD)","height")
bin_row("ASA 3+, n (%)","asa3")
bin_row("Emergency surgery, n (%)","emop")
bin_row("Knee vs hip, n (%)","knee")
cat_row("Race","race")
cont_row("LOS (days), median [IQR]","los_days",fmt="median")
bin_row("ICU admission, n (%)","icu_admit")

table1_full = pd.DataFrame(rows, columns=["Variable",
    f"General (n={len(G)})", f"Neuraxial (n={len(N)})", "SMD", "Missing"])
print(table1_full.to_string(index=False))

# c-statistic (AUC) for the ICU model
m_icu = smf.logit("icu_admit ~ neuraxial + age + female + C(asa_cat) + emop + C(proc)",
                  data=d).fit(disp=False)
auc = roc_auc_score(d["icu_admit"], m_icu.predict(d))
print(f"\nICU model c-statistic (AUC): {auc:.3f}")

# save
table1_full.to_csv(DATA_DIR/"table1_full.csv", index=False)
print("saved table1_full.csv")

d_arth.groupby('antype')['los_days'].describe()

import numpy as np, pandas as pd
import statsmodels.api as sm
import statsmodels.formula.api as smf

d = d_arth.copy()
rhs = "neuraxial + age + female + C(asa_cat) + emop + C(proc)"

m = smf.glm(f"los_days ~ {rhs}", data=d,
            family=sm.families.Gamma(link=sm.families.links.Log())).fit()

dev_ratio    = m.deviance / m.df_resid
pearson_disp = m.pearson_chi2 / m.df_resid
null = smf.glm("los_days ~ 1", data=d,
               family=sm.families.Gamma(link=sm.families.links.Log())).fit()
pseudo_r2 = 1 - m.deviance/null.deviance
ols = smf.ols(f"np.log(los_days) ~ {rhs}", data=d).fit()  # log-normal comparator

print("GAMMA LOS MODEL DIAGNOSTICS")
print(f"  deviance / df residual : {dev_ratio:.3f}")
print(f"  Pearson dispersion     : {pearson_disp:.3f}")
print(f"  pseudo-R^2 (deviance)  : {pseudo_r2:.3f}")
print(f"  Gamma AIC              : {m.aic:.1f}")
print(f"  log-normal OLS R^2     : {ols.rsquared:.3f}  (sanity comparator)")

!ls -lh "/content/run_inspire_reproducibility.py"

from google.colab import drive
drive.mount("/content/drive")

!find "/content/drive/MyDrive" -name "operations.csv.gz" -type f

!python "/content/run_inspire_reproducibility.py" \
  --data-dir "/content/drive/MyDrive/Paper1" \
  --output-dir "/content/drive/MyDrive/inspire_reproducibility_output" \
  --age-mode unknown

from pathlib import Path
hits = list(Path('/content/drive/MyDrive').rglob('run_inspire_reproducibility.py'))
print("found:", hits)

!python "/content/run_inspire_reproducibility.py" \
  --data-dir "/content/drive/MyDrive/Paper1" \
  --output-dir "/content/drive/MyDrive/inspire_reproducibility_output_v2" \
  --age-mode unknown

import json

output = "/content/drive/MyDrive/inspire_reproducibility_output_v2"

with open(f"{output}/verification_summary.json") as f:
    verification = json.load(f)

print(json.dumps(verification, indent=2))

with open(f"{output}/los_resolution_audit.json") as f:
    los_audit = json.load(f)

print(json.dumps(los_audit, indent=2))

with open(f"{output}/model_diagnostics.json") as f:
    diagnostics = json.load(f)

print(json.dumps(diagnostics, indent=2))

import pandas as pd
from pathlib import Path

output = Path("/content/drive/MyDrive/inspire_reproducibility_output_v2")

files = {
    "Primary LOS": "model_primary_los_gamma.csv",
    "Primary ICU": "model_primary_icu_logistic.csv",
    "IPTW LOS": "model_iptw_los_gamma.csv",
    "IPTW ICU": "model_iptw_icu_binomial.csv",
    "All-orthopedic LOS": "model_all_orthopedic_los.csv",
    "All-orthopedic ICU": "model_all_orthopedic_icu.csv",
    "Log-normal LOS": "model_robustness_los_lognormal.csv",
}

results = []

for analysis, filename in files.items():
    table = pd.read_csv(output / filename)
    row = table.loc[table["term"] == "neuraxial"].iloc[0]
    results.append({
        "Analysis": analysis,
        "Estimate": row["estimate"],
        "CI low": row["ci_low"],
        "CI high": row["ci_high"],
        "p-value": row["p_value"],
        "N": row["nobs"],
    })

results = pd.DataFrame(results)
display(results.round(4))

with open(f"{output}/iptw_diagnostics.json") as f:
    iptw = json.load(f)

print(json.dumps(iptw, indent=2))

balance = pd.read_csv(output / "iptw_balance.csv")
display(balance)

!cd "/content/drive/MyDrive" && zip -r \
  "inspire_reproducibility_output_v2.zip" \
  "inspire_reproducibility_output_v2"

import sys
import numpy
import pandas
import scipy
import statsmodels
import sklearn

print("Python:", sys.version)
print("NumPy:", numpy.__version__)
print("pandas:", pandas.__version__)
print("SciPy:", scipy.__version__)
print("statsmodels:", statsmodels.__version__)
print("scikit-learn:", sklearn.__version__)

!pip freeze > "/content/drive/MyDrive/inspire_reproducibility_output_v2/requirements.txt"

!python "/content/drive/MyDrive/Paper1/INSPIRE_reproducibility_public/run_inspire_reproducibility.py" \
  --data-dir "/content/drive/MyDrive/Paper1" \
  --output-dir "/content/drive/MyDrive/inspire_reproducibility_output_final" \
  --age-mode banded

import json

folder = "/content/drive/MyDrive/inspire_reproducibility_output_final"

for filename in ["verification_summary.json", "disclosure_audit.json"]:
    with open(f"{folder}/{filename}") as f:
        print(filename)
        print(json.dumps(json.load(f), indent=2))

import sys
import numpy
import pandas
import scipy
import statsmodels
import sklearn

print("Python:", sys.version)
print("NumPy:", numpy.__version__)
print("pandas:", pandas.__version__)
print("SciPy:", scipy.__version__)
print("statsmodels:", statsmodels.__version__)
print("scikit-learn:", sklearn.__version__)

